import { Code2, ShoppingCart, Brain, Layout, BarChart3, RefreshCw } from "lucide-react"

export const services = [
    {
        slug: "custom-software-development",
        icon: Code2,
        title: "Custom Software Development",
        description: "Scalable, secure, and high-performance applications tailored to your unique business needs.",
        hero: {
            headline: "Custom Software Built for Scale & Speed.",
            subhead: "We design and develop bespoke software solutions that solve your specific business challenges and drive efficiency.",
        },
        problems: [
            "Legacy systems slowing down operations",
            "Inability to scale with growing user base",
            "Security vulnerabilities in current software",
            "Disparate systems that don't talk to each other",
        ],
        deliverables: [
            "Enterprise Web Applications",
            "Mobile App Development (iOS & Android)",
            "API Development & Integration",
            "Cloud Infrastructure Setup",
        ],
        process: [
            { title: "Requirement Analysis", description: "Understanding your specific needs." },
            { title: "Architecture Design", description: "Planning a robust technical foundation." },
            { title: "Agile Development", description: "Iterative sprints for rapid delivery." },
            { title: "Deployment & CI/CD", description: "Automated pipelines for reliable releases." },
        ],
        tech: ["TypeScript", "Python", "Go", "Next.js", "React", "Node.js", "AWS", "Azure"],
        faqs: [
            { question: "How long does a typical project take?", answer: "Timelines vary based on complexity, but most MVPs are delivered in 3-4 months." },
            { question: "Do you provide post-launch support?", answer: "Yes, we offer comprehensive maintenance and support packages." },
            { question: "Do I own the code?", answer: "Absolutely. You own 100% of the intellectual property upon final payment." },
        ],
    },
    {
        slug: "e-commerce-solutions",
        icon: ShoppingCart,
        title: "E-commerce Solutions",
        description: "Seamless shopping experiences that convert visitors into loyal customers.",
        hero: {
            headline: "E-commerce That Converts.",
            subhead: "We build high-performance online stores that drive sales and customer loyalty.",
        },
        problems: [
            "High cart abandonment rates",
            "Slow page load times affecting SEO",
            "Complex inventory management issues",
            "Poor mobile user experience",
        ],
        deliverables: [
            "Custom Shopify/WooCommerce Themes",
            "Headless E-commerce Builds",
            "Payment Gateway Integration",
            "Inventory Management Systems",
        ],
        process: [
            { title: "UX Audit", description: "Analyzing current friction points." },
            { title: "Platform Selection", description: "Choosing the right tech stack." },
            { title: "Design & Dev", description: "Building a conversion-focused UI." },
            { title: "Launch & Optimize", description: "Going live and A/B testing." },
        ],
        tech: ["Shopify", "WooCommerce", "Magento", "Stripe", "PayPal", "Next.js Commerce"],
        faqs: [
            { question: "Can you migrate my existing store?", answer: "Yes, we specialize in seamless platform migrations with zero data loss." },
            { question: "Do you optimize for mobile?", answer: "All our e-commerce solutions are mobile-first and fully responsive." },
        ],
    },
    {
        slug: "ai-solutions",
        icon: Brain,
        title: "AI Solutions",
        description: "Intelligent algorithms and machine learning models that automate and optimize.",
        hero: {
            headline: "Unlock the Power of AI.",
            subhead: "Leverage machine learning and artificial intelligence to automate processes and gain predictive insights.",
        },
        problems: [
            "Manual, repetitive tasks eating up time",
            "Unstructured data that's hard to analyze",
            "Lack of personalized customer experiences",
            "Inefficient resource allocation",
        ],
        deliverables: [
            "Custom ML Models",
            "NLP Chatbots & Assistants",
            "Predictive Analytics Dashboards",
            "Computer Vision Systems",
        ],
        process: [
            { title: "Data Assessment", description: "Evaluating your data quality." },
            { title: "Model Training", description: "Developing custom algorithms." },
            { title: "Integration", description: "Embedding AI into workflows." },
            { title: "Monitoring", description: "Ensuring model accuracy over time." },
        ],
        tech: ["Python", "TensorFlow", "PyTorch", "OpenAI API", "Hugging Face", "Pinecone"],
        faqs: [
            { question: "Do I need a lot of data?", answer: "Not necessarily. We can start with pre-trained models and fine-tune them." },
            { question: "Is my data secure?", answer: "We adhere to strict data privacy standards and can deploy on-premise if needed." },
        ],
    },
    {
        slug: "ui-ux-design",
        icon: Layout,
        title: "UI/UX Design",
        description: "Intuitive, user-centric designs that delight users and enhance engagement.",
        hero: {
            headline: "Design That Delights.",
            subhead: "We craft intuitive user interfaces and engaging experiences that users love.",
        },
        problems: [
            "Low user engagement or retention",
            "Confusing navigation or information architecture",
            "Outdated visual identity",
            "Inconsistent branding across platforms",
        ],
        deliverables: [
            "User Research & Personas",
            "Wireframes & Prototyping",
            "High-Fidelity UI Design",
            "Design Systems",
        ],
        process: [
            { title: "Research", description: "Understanding user needs." },
            { title: "Ideation", description: "Brainstorming solutions." },
            { title: "Prototyping", description: "Testing concepts." },
            { title: "Handoff", description: "Preparing assets for dev." },
        ],
        tech: ["Figma", "Adobe XD", "Sketch", "Principle", "Storybook"],
        faqs: [
            { question: "Do you do user testing?", answer: "Yes, we conduct usability testing to validate our designs." },
            { question: "Can you work with our existing brand?", answer: "Absolutely. We can evolve your brand or work strictly within guidelines." },
        ],
    },
    {
        slug: "business-intelligence",
        icon: BarChart3,
        title: "Business Intelligence",
        description: "Data-driven insights to make informed strategic decisions.",
        hero: {
            headline: "Turn Data into Decisions.",
            subhead: "We build BI dashboards and data pipelines that give you real-time visibility into your business.",
        },
        problems: [
            "Siloed data across departments",
            "Manual reporting in spreadsheets",
            "Lack of real-time KPIs",
            "Difficulty forecasting trends",
        ],
        deliverables: [
            "Data Warehousing",
            "ETL Pipeline Development",
            "Interactive Dashboards",
            "Automated Reporting",
        ],
        process: [
            { title: "Data Audit", description: "Mapping data sources." },
            { title: "Pipeline Build", description: "Connecting data streams." },
            { title: "Visualization", description: "Creating dashboards." },
            { title: "Training", description: "Empowering your team." },
        ],
        tech: ["Power BI", "Tableau", "Looker", "Snowflake", "BigQuery", "dbt"],
        faqs: [
            { question: "Can you connect to legacy databases?", answer: "Yes, we can ingest data from almost any source." },
            { question: "Is it real-time?", answer: "We can set up near real-time streaming or scheduled batch processing." },
        ],
    },
    {
        slug: "digital-transformation",
        icon: RefreshCw,
        title: "Digital Transformation",
        description: "Modernize your legacy systems and embrace the future of digital business.",
        hero: {
            headline: "Evolve or Get Left Behind.",
            subhead: "We help established enterprises modernize their technology stack and culture for the digital age.",
        },
        problems: [
            "Outdated legacy systems",
            "Slow time-to-market",
            "Resistance to change",
            "Inefficient manual workflows",
        ],
        deliverables: [
            "Technology Roadmap",
            "Cloud Migration",
            "Process Automation",
            "Change Management",
        ],
        process: [
            { title: "Assessment", description: "Evaluating current state." },
            { title: "Strategy", description: "Defining the roadmap." },
            { title: "Execution", description: "Implementing changes." },
            { title: "Optimization", description: "Continuous improvement." },
        ],
        tech: ["Cloud Native", "Microservices", "DevOps", "Agile Methodologies"],
        faqs: [
            { question: "How do you handle change management?", answer: "We work closely with your team to ensure adoption and minimize resistance." },
            { question: "What is the ROI?", answer: "We focus on high-impact areas first to demonstrate quick wins and ROI." },
        ],
    },
]

export const caseStudies = [
    {
        slug: "fintech-transformation",
        title: "FinTech Transformation",
        category: "Digital Transformation",
        client: "FinTech Corp",
        industry: "Financial Services",
        challenge: "Legacy infrastructure was preventing the launch of new real-time payment features, causing customer churn.",
        approach: "We re-architected the core banking core using microservices and event-driven architecture.",
        solution: "A scalable, cloud-native platform capable of processing millions of transactions per second.",
        results: [
            { label: "Transaction Speed", value: "10x Faster" },
            { label: "Uptime", value: "99.99%" },
            { label: "Dev Velocity", value: "+300%" },
        ],
        testimonial: {
            quote: "Nexusnao transformed our legacy system into a modern powerhouse. Their team is exceptional.",
            author: "Jane Doe",
            role: "CTO",
        },
        stack: ["Go", "Kafka", "Kubernetes", "AWS"],
        timeline: "12 Months",
        team: "12 Engineers, 2 Designers, 1 PM",
    },
    {
        slug: "ai-analytics",
        title: "AI-Powered Analytics",
        category: "AI Solutions",
        client: "RetailAI",
        industry: "Retail",
        challenge: "The client had massive amounts of customer data but no way to generate actionable insights in real-time.",
        approach: "We built a custom machine learning pipeline to analyze customer behavior and predict trends.",
        solution: "A predictive analytics dashboard that helps store managers optimize inventory and staffing.",
        results: [
            { label: "Operational Costs", value: "-30%" },
            { label: "Inventory Waste", value: "-25%" },
            { label: "Sales Growth", value: "+15%" },
        ],
        testimonial: {
            quote: "The AI solution they built saved us 30% in operational costs. Highly recommended.",
            author: "John Smith",
            role: "Founder",
        },
        stack: ["Python", "TensorFlow", "React", "BigQuery"],
        timeline: "6 Months",
        team: "4 ML Engineers, 2 Full Stack Devs",
    },
    {
        slug: "global-ecommerce",
        title: "Global E-commerce Platform",
        category: "E-commerce",
        client: "StyleGlobal",
        industry: "Fashion",
        challenge: "The existing monolithic platform crashed during peak traffic and couldn't support multi-currency sales.",
        approach: "We migrated to a headless commerce architecture with a global CDN and edge computing.",
        solution: "A lightning-fast, globally distributed shopping experience with localized content.",
        results: [
            { label: "Page Load Time", value: "0.8s" },
            { label: "Conversion Rate", value: "+45%" },
            { label: "Global Sales", value: "+200%" },
        ],
        testimonial: {
            quote: "Our new site is blazing fast anywhere in the world. Nexusnao delivered beyond expectations.",
            author: "Sarah Lee",
            role: "VP of Digital",
        },
        stack: ["Next.js", "Shopify Plus", "Sanity", "Vercel"],
        timeline: "8 Months",
        team: "6 Engineers, 3 Designers",
    },
]
